#!/usr/bin/env bash

echo 'Running commit script'

GIT_ROOT_DIRECTORY=$(git rev-parse --show-toplevel)
CUSTOM_IGNORED_PATH="$GIT_ROOT_DIRECTORY/.smart-commit-ignore"

IGNORED_BRANCHES=("dev" "master" "qa" "uat" "staging")

if [ -f "$CUSTOM_IGNORED_PATH" ]
then
    CUSTOM_BRANCHES=$(cat "$CUSTOM_IGNORED_PATH")
    BRANCHES=($CUSTOM_BRANCHES)
    IGNORED_BRANCHES=(${IGNORED_BRANCHES[@]} ${BRANCHES[@]})
fi

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

COMMIT_WITH_BRANCH="git commit -m \"$CURRENT_BRANCH: $1\""
DEFAULT_COMMIT="git commit -m \"$1\""

IS_IGNORED=false

for branch in "${IGNORED_BRANCHES[@]}";
    do
        if [ "$CURRENT_BRANCH" == $branch ]
        then
            IS_IGNORED=true
	    break
	fi
done

if [ "$IS_IGNORED" == false ]
then
    echo "Commiting with branch name -> $CURRENT_BRANCH"
    eval $COMMIT_WITH_BRANCH
else
    eval $DEFAULT_COMMIT
fi
