name: Bats Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git configurations
      run: |
        git config --global user.name "CI User"
        git config --global user.email "ci@example.com"

    - name: Set up Git
      run: |
        sudo apt-get update
        sudo apt-get install -y git

    - name: Install Bats
      run: sudo apt-get install bats

    - name: Run Bats tests
      run: |
        bats tests.bats
